name: CI Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc[s3]    # Use appropriate extra if you use s3/gcs/azure/etc
          pip install pytest

      - name: DVC Pull
        run: dvc pull
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # Add matching env vars for your remote storage if needed

      - name: Run Tests
        run: pytest --maxfail=1 --disable-warnings -q > result.log; exit 0

      - name: Sanity Report with CML
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install cml
          echo "## Test Result" > report.md
          tail -n 20 result.log >> report.md
          cml comment create report.md
